### ISSUE TITLE
Memory Leak in GraphDB During Bulk SPARQL Triple Insertions

### ISSUE THREAD

**Issue by Myasir92** [Ontotext-AD/graphdb-workbench#1379]
We are experiencing a critical issue with GraphDB running in a Docker container, where it crashes due to excessive memory usage during the insertion of triples using SPARQL queries. The problem occurs when the number of triples approaches or exceeds 1 million. Although restarting GraphDB resolves the high memory consumption temporarily, this is not a sustainable solution.

Current behavior:
- GraphDB crashes when inserting approximately 1 million triples via SPARQL, with each query inserting about 7-8 triples.
- Memory usage spikes significantly until the system becomes unresponsive and crashes.
- Restarting the GraphDB container temporarily mitigates the issue by reducing memory usage.

Expected behavior:
- GraphDB should handle bulk triple insertions efficiently without excessive memory consumption or crashing.
- There should be a mechanism to manage or release memory actively during the bulk insertion process.

This issue affects our data processing capabilities and requires an urgent fix. We would appreciate any insights or recommendations on how to address this memory management problem in GraphDB.

**Comment by MartinaDimova** [comment]
Hello Muhammad Yasir, 
This seems to be GraphDB's engine related issue while this is GitHub repo for the workbench, which is an open-source separated project related only to the UI of GraphDB. We apprecaite your understanding and transfering the discussion to the official support mail which is graphdb-support.ontotext.com.
Additionally, we're looking forward to our meeting next week with one of our solution architects and devOps experts.
