### ISSUE TITLE
Plaintext passwords in connectors

### ISSUE THREAD

**Issue by ThomasThelen** [Ontotext-AD/graphdb-workbench#1533]
I noticed that after adding an elasticsearch connector - the password is shown in plaintext when viewing it. This is a security risk that now, if someone gets access to the workbench they can view the passwords for other services.

I would expect there to be some sort of hashed storage of the password and it be shown as a masked value in the workbench.

To reproduce:

1. Create a new connector
2. View the connectors for the repository
3. Open the connector
4. Scroll down to see the password
5. Check the network tab and see the password in plaintext

**Comment by svilenvelikov** [comment]
@ThomasThelen thank you again for reporting this. I'm passing this down to the team to decide how to deal with it.

**Comment by svilenvelikov** [comment]
The user would see these passwords only if he/she has write access for the respective repository or in other words to create or delete connectors. It appears that it's implemented this way by design.

**Comment by ThomasThelen** [comment]
Fair enough. I just don't this behavior in mainstream products. Seems more like a workaround for editing the connector without having to re-enter the password. Close if you want

**Comment by svilenvelikov** [comment]
Yes. Exactly. I agree that it's not optimal but the team is kind of reluctant to do some changes in this behavior at the moment.
