### ISSUE TITLE
graphdb 9.x has miscalculations in processing default.min.distinct.threshold seeting

### ISSUE THREAD

**Issue by antonkulaga** [Ontotext-AD/graphdb-workbench#213]
I constantly get:
```
Press Alt+Enter to autocomplete
Operation took 21s, moments ago.
Error 500: error
Insufficient free Heap Memory 21,042Mb for group by and distinct, threshold:36,864Mb, reached 37Mb
```
That is very weird as 36,864Mb is 1000 times more than 37Mb I think you have a serious threshold miscalculation in GraphDB Free 
My config is https://github.com/antonkulaga/bigdata-docker/blob/master/bigdata.yml#L105
I have 64 GB RAM on the machine and I medium size database of 1,471,447,540 statements and I am constantly getting such errors.
![Screenshot_2020-05-05 SPARQL Query Update GraphDB Workbench](https://user-images.githubusercontent.com/842436/81029913-7ef9f780-8e8f-11ea-948a-3faa361a6479.png)

**Comment by antonkulaga** [comment]
@desislava-hristova-ontotext I am really struggling with this issue as it pops up everywhere (with all types of quries) and I have no idea why.

**Comment by desislava-hristova-ontotext** [comment]
Hi, and sorry for the delayed response. Seems that this is not an issue with graphdb-workbench UI but with GraphDB engine configuration. I am sending your issue to the GraphDB support email.

**Comment by konstantinspetrov** [comment]
The lower the threshhold, the less likely you will get those errors. It basically means - if the memory falls below this threshhold thrown an error.

**Comment by antonkulaga** [comment]
Thank you very much, I indeed misunderstood the threshold. I am also grateful to Sava Savov for his recommendations
