### ISSUE TITLE
Cannot start app's webpack dev server

### ISSUE THREAD

**Issue by stepharr** [Ontotext-AD/graphdb-workbench#237]
Hi I am trying to get the webpack dev server running but running into some issues. When I run `npm run start` I get the error
```
[HPM] Error occurred while trying to proxy request /rest/info/version?local=1 from localhost:9000 to http://localhost:7200 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```
The load screen just stays stuck. I tried making sure the ports didn't have conflicts, changing the ports, changing the host to '0.0.0.0', but nothing fixed this issue. I've tried this on a Mac and Windows, and ran into this issue.  I also looked into some suggestions from this issue: https://github.com/saikat/react-apollo-starter-kit/issues/20. I tried changing the host to `[::1]` but then got the error:

```
Error: getaddrinfo ENOTFOUND [::1]
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)
Emitted 'error' event on Server instance at:
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1484:12)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:17) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '[::1]'
}
```
I expected to run `npm run start` and the application start without issue. Any suggestions on how to get it to start without error?

**Comment by avataar** [comment]
Judging by the error message you don't have a running GraphDB instance on localhost:7200. The workbench requires an existing GraphDB instance to proxy requests to as it doesn't contain GraphDB proper itself.

**Comment by stepharr** [comment]
Yup! I'll close this ticket.
