### ISSUE TITLE
'Raw Response' tab showing only up to 100 results

### ISSUE THREAD

**Issue by mommi84** [Ontotext-AD/graphdb-workbench#471]
## Environment
macOS Catalina 10.15.7
GraphDB Free 9.8.0

## Issue 
Even when the number of records shown in the 'Table' tab after a SPARQL query is higher than 100, the 'Raw Response' tab shows only up to 100 JSON results. This is misleading. At least a warning to the user should be given.

**Comment by nikolaykolev** [comment]
Fixed in GraphDB 10.2
